### ISSUE TITLE
bug: Documentation

### ISSUE THREAD

**Issue by maelp** [robingenz/capacitor-mlkit-plugin-demo#13]
It's not very clear from the documentation what to do for Android, for instance if we don't want to have the user click on "install Google barcode", but do it automatically on the first scan:

- shoudl we call isGoogleBarcodeScannerModuleAvailable each time or only the first time?
- in this case, how do we know if the plugin was already successfully installed?

**Comment by robingenz** [comment]
> It's not very clear from the documentation what to do for Android, for instance if we don't want to have the user click on "install Google barcode", but do it automatically on the first scan:

This demo app is only for developers to test the individual plugin APIs and is not meant for the end user.
See also https://github.com/capawesome-team/capacitor-mlkit/discussions/84#discussioncomment-7249913.

> shoudl we call isGoogleBarcodeScannerModuleAvailable each time or only the first time?

You should call it each time.

> in this case, how do we know if the plugin was already successfully installed?

If `isGoogleBarcodeScannerModuleAvailable(...)` returns `{ available: true }`, then the module was successfully installed.

**Comment by maelp** [comment]
Okay! That wasn’t immediately clear to me 😅I thought is available meant « is compatible with my phone and I can go on and download it », and not « is already installed »Perhaps renaming it to is installed would clarify?On Nov 2, 2023, at 11:36, Robin Genz ***@***.***> wrote:﻿

It's not very clear from the documentation what to do for Android, for instance if we don't want to have the user click on "install Google barcode", but do it automatically on the first scan:

This demo app is only for developers to test the individual plugin APIs and is not meant for the end user.
See also capawesome-team/capacitor-mlkit#84 (comment).

shoudl we call isGoogleBarcodeScannerModuleAvailable each time or only the first time?

You should call it each time.

in this case, how do we know if the plugin was already successfully installed?

If isGoogleBarcodeScannerModuleAvailable(...) returns { available: true }, then the module was successfully installed.

**Comment by robingenz** [comment]
> Perhaps renaming it to is installed would clarify

Yes, I will probably do that in the next major release.

In this case i am closing this issue.
