### ISSUE TITLE
feat: adjust scanning frequency or add throttling? 

### ISSUE THREAD

**Issue by corpro** [robingenz/capacitor-mlkit-plugin-demo#15]
Hi Robin,

I’ve been using the plugin in a project for scanning linear formats, thank you for taking the time to build it.  The speed is awesome for most of the time. I do specify the formats before scanning but sometimes the scan is slow.   I’ve been playing around with this barcode scanning app https://qrbot.net/locale/en/ which is consistently fast.  I believe camera focusing is the key to the speed.  Also positioning the barcode vertically seems to keep the scanning speed consistent.  Is there a way to adjust scanning frequency or add throttling? 

Thanks, Corey

**Comment by robingenz** [comment]
Thank you, i will take a look at it. Can you share a screen recording with some examples?

**Comment by corpro** [comment]
https://github.com/robingenz/capacitor-mlkit-plugin-demo/assets/13640080/a98b0066-7c63-4ae6-8d56-2b4c5cdd9aed

**Comment by corpro** [comment]
Hi Robin,

I have spent the past few days scanning, and I've discovered that starting at a distance of 12 inches and gradually moving the phone towards the barcode yields the best results. I can consistently achieve good outcomes.

Thank you again for the hard work you've put into this project

**Comment by robingenz** [comment]
I assume that the computed coordinates are not quite correct yet and that the barcode is recognized much earlier.
You can check this by setting a `console.log(...)` in the following line: https://github.com/robingenz/capacitor-mlkit-plugin-demo/blob/e4b809662bf177f18a77efc0d53623994cd4ad6c/src/app/modules/barcode-scanning/barcode-scanning-modal.component.ts#L176

**Comment by corpro** [comment]
Hi Robin,

One other issue I have experienced is I can scan the same barcode multiple times, at least five times and then randomly I get a different code. The code is usually only off by a number but sometimes it's completely different. Have you experienced this?

Thanks, Corey

**Comment by robingenz** [comment]
I assume that the first problem has been solved. I am therefore closing this issue.

Regarding the second issue, there is already an open issue for that: https://github.com/capawesome-team/capacitor-mlkit/issues/96
