### ISSUE TITLE
Android Error

### ISSUE THREAD

**Issue by corpro** [robingenz/capacitor-mlkit-plugin-demo#16]
Hi Robin,

I am not experienced in Android Studio but I keep getting this error using your demo app

Capacitor/Console       io.ionic.starter                     E  File: https://localhost/main.09a9529574ac6b42.js - Line 1 - Msg: ERROR Error: 17: API: ModuleInstall.API is not available on this device. Connection failed with: ConnectionResult{statusCode=SERVICE_INVALID, resolution=null, message=null}

Any suggestions?

Thanks

**Comment by robingenz** [comment]
Thank you for your request.
It seems like you are using an Android device without Google Play Services. This means that you cannot use the `scan(...)` method/button, only the `startScan(...)` method/button.

**Comment by corpro** [comment]
I set implementation 'com.google.android.gms:play-services-mlkit-barcode-scanning:18.3.0
and 
<meta-data
            android:name="com.google.mlkit.vision.DEPENDENCIES" android:value="barcode" ></meta-data>

**Comment by robingenz** [comment]
As i said, it seems like you are using an Android device without Google Play Services. This has nothing to do with missing dependencies.
