### ISSUE TITLE
Versiones de android

### ISSUE THREAD

**Issue by AuxSistemasLitoral** [robingenz/capacitor-mlkit-plugin-demo#17]
Hi @robingenz  !
In advance I want to thank you for the plugin, it saved my app, I have a question regarding the Android versions.
I created an app and installed the plugin and created an APK that is not signed to be used as a third party, but it only works for versions 13 and 14, for versions 11 or lower it gives me an error and tells me that the module is not installed. the version I installed is the
"@capacitor-mlkit/barcode-scanning": "^5.3.0".
What version can I use so that it runs on devices with Android 11 or lower?
In those versions the rest of my application behaves as expected and only the scanner gives me errors.

**Comment by robingenz** [comment]
Please take a look at this comment: https://github.com/capawesome-team/capacitor-mlkit/issues/38#issuecomment-1626891989
I will close this issue since it is not related to this demo app.
