### ISSUE TITLE
IOS issue 

### ISSUE THREAD

**Issue by cvetdeag** [robingenz/capacitor-mlkit-plugin-demo#18]
**Describe the bug**
When starting a scan on an IOS device (16.1) the webview is just a black screen with the viewfinder but I am getting correct scan results.

**To Reproduce**
I followed the instructions to install and run the example app on an IOS device.

**Expected behavior**
The camera content should be visible.

**Screenshots**
will be added

**Smartphone (please complete the following information):**

- Device: [e.g. iPhoneSE]
- OS: [e.g. iOS16.1]

**Additional context**
I am using the plugin already in a React project and this example application was used for verification purposes. Both versions are running fine even on Android 9.0 (SDK 28). 
Unfortunately I am not able to test on a higher IOS version due to HW constraints.

**Comment by robingenz** [comment]
Did you request camera permissions?

**Comment by cvetdeag** [comment]
Yes, added the info.plist entry.

**Comment by robingenz** [comment]
No need to configure anything. You just need to press the "Request Permissions" button.

**Comment by cvetdeag** [comment]
Apparently there’s a misunderstanding from my side. 
I have to call requestpermission before the scan in order webview is becoming visible?
I thought I am set with the info.plist setting.

**Comment by robingenz** [comment]
Yes, you have to request the camera permission at runtime before the scan starts.

**Comment by cvetdeag** [comment]
ok. I need to verify. but I need some time as I do not have my mac equipment at hand.

**Comment by cvetdeag** [comment]
I was able to test today. the issue is not related to the permissions. The scan is working and I am getting a result but I am still not seeing the webview. I am using ionic v 7.1.5 with React.
I tried your example and it works.

2024-02-02 20:20:52.879223+0100 App[824:72777] KeyboardPlugin: resize mode - native
⚡️ Warning: isWebDebuggable only functions as intended on iOS 16.4 and above.
⚡️  Loading app at capacitor://localhost...
2024-02-02 20:20:53.004199+0100 App[824:72777] [Sandbox] Could not enable Mach bootstrap, errno = 1.
2024-02-02 20:20:53.004374+0100 App[824:72777] [Sandbox] Could not enable Mach bootstrap, errno = 1.
⚡️  WebView loaded
⚡️  To Native ->  BarcodeScanner isSupported 68285574
⚡️  TO JS {"supported":true}
⚡️  To Native ->  App addListener 68285575
⚡️  To Native ->  BarcodeScanner requestPermissions 68285576
⚡️  To Native ->  Keyboard getResizeMode 68285577
⚡️  TO JS {"mode":"native"}
⚡️  TO JS {"camera":"granted"}
⚡️  To Native ->  BarcodeScanner addListener 68285578
⚡️  To Native ->  BarcodeScanner startScan 68285579
2024-02-02 20:20:55.780273+0100 App[824:72777] Initialized TensorFlow Lite runtime.
INFO: Initialized TensorFlow Lite runtime.
2024-02-02 20:20:55.809339+0100 App[824:72777] Created TensorFlow Lite XNNPACK delegate for CPU.
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
⚡️  TO JS undefined
2024-02-02 20:20:56.411780+0100 App[824:72777] [Accessibility] WKContentView[@] set up: @ pid: @ MACH_PORT 1107428352
⚡️  TO JS {"barcode":{"rawValue":"4066600603405","cornerPoints":[[277,719],[311,716],[303,1049],[269,1057]],"valueType":"PRODUCT","bytes":[52,48,54,54,54,48,48,54,48,51,52,48,53],"format":"EAN_13","displayValue":"4066600603405"}}
⚡️  [log] - Scanned Barcode {"barcode":{"rawValue":"4066600603405","cornerPoints":[[277,719],[311,716],[303,1049],[269,1057]],"valueType":"PRODUCT","bytes":[52,48,54,54,54,48,48,54,48,51,52,48,53],"format":"EAN_13","displayValue":"4066600603405"}}

Any idea?

**Comment by robingenz** [comment]
> I tried your example and it works.

In this case, I am closing this issue as it does not look like an issue with this demo app.

Without a minimal, reproducible example, I cannot debug the problem. Please create a new issue in this repository: https://github.com/capawesome-team/capacitor-mlkit
