### ISSUE TITLE
Property 'setZoomRatio' does not exist on type 'BarcodeScannerPlugin'

### ISSUE THREAD

**Issue by Qberon** [robingenz/capacitor-mlkit-plugin-demo#19]
As well as
Property 'getMinZoomRatio' does not exist on type 'BarcodeScannerPlugin'
Property 'getMaxZoomRatio' does not exist on type 'BarcodeScannerPlugin'.

all errors in barcode-scanning-modal.component.ts

**Comment by robingenz** [comment]
I cannot reproduce this issue. As you can see, the build runs successfully: https://github.com/robingenz/capacitor-mlkit-plugin-demo/actions/runs/7357741641/job/20029860670
