### ISSUE TITLE
feat: green labeling 

### ISSUE THREAD

**Issue by corpro** [robingenz/capacitor-mlkit-plugin-demo#20]
Hi Robin,

I have been testing the mlkit IOS demo app found here: https://github.com/googlesamples/mlkit/tree/master/ios/quickstarts/vision

The barcode detection is noticeably better which includes a green label. Is this something you would consider adding and updating the code to match the demo version?  In the attached video I wasn’t able to scan this barcode with your version. 

https://github.com/robingenz/capacitor-mlkit-plugin-demo/assets/13640080/2531358d-2b10-44ff-b044-4bef0b4e46b9

**Comment by robingenz** [comment]
Thank you for your request. I currently don't plan to add this feature. I want to keep this demo app as simple as possible.
