### ISSUE TITLE
feat: integrate the @capawesome/capacitor-torch as the 'BarcodeScanner.toggleTorch' is deprecated

### ISSUE THREAD

**Issue by umeshsarkar** [robingenz/capacitor-mlkit-plugin-demo#27]
In the latest @capacitor-mlkit/barcode-scanning (6.2.0) update, the `BarcodeScanner.toggleTorch ` is deprecated. 

The solution recommended is to use @capawesome/capacitor-torch. I tried to implement this plugin but I received the error as mentioned below.  
```
CapacitorException: CAMERA_IN_USE (4): setTorchMode:3057: Torch for camera "0" is not available due to an existing camera user
    at returnResult (<anonymous>:943:32)
    at win.androidBridge.onmessage (<anonymous>:918:21)
```

Test was done in the Pixel 6a device and Android version 14. 

I have tried the `@capawesome/capacitor-torch` in the [robingenz](https://github.com/robingenz)/[capacitor-mlkit-plugin-demo](https://github.com/robingenz/capacitor-mlkit-plugin-demo)

**Comment by robingenz** [comment]
Good catch! It seems that there is no way to access the same camera from two different processes. For this reason I will remove the deprecation in the ML Kit Barcode Scanning plugin for the time being.

**Comment by umeshsarkar** [comment]
Thank you! The issue https://github.com/capawesome-team/capacitor-mlkit/issues/185 can also be closed.
