### ISSUE TITLE
bug: barcode-scanning conflict with photoviewer plugin

### ISSUE THREAD

**Issue by rkreutzer** [robingenz/capacitor-mlkit-plugin-demo#29]
**Describe the bug**
The barcode-scanning plugin startScan method returns "Attempt to invoke virtual method 'void androidx.camera.view.PreviewView.setScaleType(androidx.camera.view.PreviewView$ScaleType)' on a null object reference" when used in the same app as @capacitor-community/photoviewer.
Photoviewer works independently and with barcode-scanning.
Barcode-scanning works independently, but not with photoviewer.

**To Reproduce**
In the example app, install @capacitor-community/photoviewer, then do the installation steps for Android. Then build and run.

**Expected behavior**
Both plugins should work correctly together. Both plugins require dataBinding, so best guess is the issue has something to do with that.

**Smartphone **

- Device: Android
- OS: Pie thru 34
- Version 6.2.0
- Capacitor 6.2.0
- Ionic 6.7.5
- Angular 17.3.12

**Comment by robingenz** [comment]
Please create a bug report in the [plugin repository](https://github.com/capawesome-team/capacitor-mlkit). The Photoviewer plugin is not part of that demo app.
